version: '3'
services:
  workspace:
    # build: .
    image: giffon/charleywong_devcontainer_workspace:20200712
    volumes:
      - ..:/workspace:cached
    environment:
      - HUB_HOST=selenium
    user: user
    command: sleep infinity
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-yttrium
    environment:
      - VNC_NO_PASSWORD=1
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
