version: '3'
services:
  workspace:
    # build: .
    image: giffon/charleywong_devcontainer_workspace:20201124
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    user: user
    command: sleep infinity

volumes:
  node_modules:
