name: Update meta

on:
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  job:
    runs-on: ubuntu-latest
    container: giffon/charleywong_devcontainer_workspace:20200712
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          ref: meta
      - name: Setup Python virtualenv
        shell: bash
        run: |
          set -ex
          python3 -m virtualenv -p /usr/bin/python3.7 --no-pip ~/venv
          source ~/venv/bin/activate
          curl -sSLf https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py pip==19.3.1
          pip3 install -r requirements.txt
      - name: Install libraries
        run: |
          set -ex
          npm install
          bash build-dclookup.sh
          haxelib newrepo
          haxelib install syncFacebook.hxml --always -notimeout
      - name: Compile
        run: haxe syncFacebook.hxml
      - name: Import gpg key
        run: |
          echo "${#CBCA760DC1170A9B}"
          echo "$CBCA760DC1170A9B" | gpg --import
        env:
          CBCA760DC1170A9B: ${{ secrets.CBCA760DC1170A9B }}
      - name: Run
        run: node syncFacebook.js updateMeta "Charley Wong's bot <charleywong-bot@giffon.io>" "CBCA760DC1170A9B!" "https://charleywong-bot:${BOT_PASSWORD}@github.com/giffon/charleywong.git" meta
        env:
          BOT_PASSWORD: ${{ secrets.botPassword }}
          FACEBOOK_TOKEN: ${{ secrets.FACEBOOK_TOKEN }}
